Caso de uso creación de campaña
francoo27/give pull request #3
Opened 2023-08-31 22:50 UTC by francoo27

2023-09-02 19:59 UTC, FedericoRuiz98 requested changes

2023-09-02 19:59 UTC, FedericoRuiz98 commented on documentation/CU-crear-campaña.md
> +5. Luego, en el **Paso 3: Recompensas**, el usuario describe las recompensas que ofrecerá a los donantes por donar ciertos montos.
```suggestion
5. Luego, en el **Paso 3: Recompensas** (Opcional), el usuario describe las recompensas que ofrecerá a los donantes por donar ciertos montos.
```

2023-09-02 19:59 UTC, FedericoRuiz98 commented on documentation/CU-crear-campaña.md
> +6. Finalmente, en el **Paso 4: Plan de Progreso**, el usuario establece checkpoints dentro del rango de fechas de la campaña para mostrar el progreso de la misma.
```suggestion
6. Finalmente, en el **Paso 4: Plan de Progreso** (Opcional), el usuario establece checkpoints dentro del rango de fechas de la campaña para mostrar el progreso de la misma.
```

2023-09-02 19:59 UTC, FedericoRuiz98 commented on documentation/CU-crear-campaña.md
> +   - La campaña queda en estado PAUSADA, esperando su validación.
Para el paso 9 creo que deberiamos contemplar la posibilidad de que las capañas puedan comenzar de inmediato para no saturar a los moderadores.

- En casos de montos bajos (menos de 10.000 ARS)
  - hay que validar que no se puedan crear muchas campañas seguidas para **evitar casos de lavado de dinero** pasando por debajo del limite que decidamos, podemos establecer un numero maximo de campañas por mes?
- Fecha de creacion/fin muy cercanas a la fecha de hoy (menos de mes por ejemplo)

2023-09-02 21:52 UTC, francoo27 commented on documentation/CU-crear-campaña.md
> +   - La campaña queda en estado PAUSADA, esperando su validación.
> En casos de montos bajos (menos de 10.000 ARS)
> * hay que validar que no se puedan crear muchas campañas seguidas para **evitar casos de lavado de dinero** pasando por debajo del limite que decidamos, podemos establecer un numero máximo de campañas por mes?
Resolvemos que vamos a crear un archivo para las reglas de negocio

2023-09-02 22:02 UTC, francoo27 commented on documentation/CU-crear-campaña.md
> +   - La campaña queda en estado PAUSADA, esperando su validación.
> * Fecha de creacion/fin muy cercanas a la fecha de hoy (menos de mes por ejemplo)

Aca tenemos que modifcar el comportamiento, un Usuario va a poder crear y lanzar una campaña el mismo dia o

2023-09-03 20:57 UTC, jpcastelli58 commented
1. No estoy seguro de que el transcurso de la campaña sea el mismo CU que la creación, la parte de como termina c/u para mí sería otro CU, además porque de ahí se dispararían los CU de actualizar historial y ponderación del usuario, lo de la validación a posteriori, etc.
2. 
> Si el usuario está validado:
La campaña queda en estado PAUSADA, esperando su validación.
Si el usuario no está validado:
La campaña queda en estado ACTIVA.

No entiendo bien esta parte.

3. ¿Y si la validación sólo te da un check de validado pero no es que te restrinja?
4. Faltaría un paso opcional donde el usuario pueda subir las pruebas a priori, y que ahí inicia otro CU.

2023-09-07 20:16 UTC, francoo27 commented on documentation/CU-crear-campaña.md
> +   - La campaña queda en estado PAUSADA, esperando su validación.
> Aca tenemos que modifcar el comportamiento, un Usuario va a poder crear y lanzar una campaña el mismo dia o

creada la regla de negocio RN 02

2023-09-11 00:11 UTC, FedericoRuiz98 approved these changes

2023-09-11 00:32 UTC, merged