Cu Pausar campaña
francoo27/give pull request #6
Opened 2023-09-07 21:02 UTC by francoo27

2023-09-11 01:16 UTC, FedericoRuiz98 requested changes

2023-09-11 01:16 UTC, FedericoRuiz98 commented on documentation/CU-pausar-campaña.md
> +**Fracaso:** Si el usuario no puede proporcionar una razón válida , el caso de uso se cancela y la campaña no se pausa.
cual seria esa razon "no valida"? implica control por parte de los moderadores el simple hecho de pausar una campaña?

2023-09-11 02:20 UTC, francoo27 commented on documentation/CU-pausar-campaña.md
> +**Fracaso:** Si el usuario no puede proporcionar una razón válida , el caso de uso se cancela y la campaña no se pausa.
Hay varias cosas y no lo se definir bien, primero que el tipo cancele el caso de uso ,osea que no quiera realmente pausarla y termine en fracaso
la otra es ver si, como vos decis, los moderadores pueden tener injerencia en si alguien puede pausar una campaña o no, habria que ver, nose si es causa de exploit

2023-09-11 03:38 UTC, jpcastelli58 commented
Hay que analizar que tanta libertar se le da al creador de la campaña para editar, por ejemplo pido 50k y llego a los 10 y veo que la cosa no avanza mas, cambio el tope a 10k para que quede como campaña exitosa, cosa que es falsa.

2023-09-15 01:48 UTC, FedericoRuiz98 commented on documentation/CU-pausar-campaña.md
> +**Fracaso:** Si el usuario no puede proporcionar una razón válida , el caso de uso se cancela y la campaña no se pausa.
no creo que genere un exploit, para mi hay que intetar reducir la interaccion con lo moderadores

2023-09-15 02:09 UTC, FedericoRuiz98 commented on documentation/CU-pausar-campaña.md
> +**Fracaso:** Si el usuario no puede proporcionar una razón válida , el caso de uso se cancela y la campaña no se pausa.
osea que se pause de una y fue

2023-09-18 21:51 UTC, FedericoRuiz98 approved these changes

2023-09-18 21:51 UTC, merged